image: node:lts

pipelines:
    branches:
        develop:
            - step:
                  caches:
                      - node
                  name: Installing dependencies using yarn
                  script:
                      - yarn install
            - step:
                  name: Compiling and Building the application
                  script:
                      - echo "Building the application scripts";
            - step:
                  name: Creating a release
                  caches:
                      - node
                  script:
                      - yarn release
