image: node:lts

pipelines:
    branches:
        develop:
            - step:
                  name: 'Checking for release commit'
                  script:
                      - echo $BITBUCKET_COMMIT
                      - echo $(git log $BITBUCKET_COMMIT -1 --oneline) > msg.txt
                      - cat msg.txt
                      - |
                          if [[ $(cat msg.txt) =~ ^.*chore\\(release\\).*$ ]]; then
                            echo "This is working";
                          else
                            echo "This is not working";
                          fi
                      - |
                          if [[ $(git log $BITBUCKET_COMMIT -1 --oneline) =~ ^.*chore\\(release\\).*$ ]]; then
                            echo "This is working";
                          else
                            echo "This is not working";
                          fi
                      - |
                          [[ $(git log $BITBUCKET_COMMIT -1 --oneline) =~ ^.*chore\\(release\\).*$ ]] && echo "This works" || echo "We fucked up"
                      - |
                          if [[ $(git log $BITBUCKET_COMMIT -1 --oneline) =~ ^.*chore\\(release\\).*$ ]]; then
                            echo $(git log $BITBUCKET_COMMIT -1 --oneline);
                            echo true > condition.txt;
                          fi
                      - ls -alF
                      - echo "Failing early to check only this step";
                      - exit 1;
                  artifacts:
                      - condition.txt
            - step:
                  caches:
                      - node
                  name: Installing dependencies using yarn
                  script:
                      - |
                          if $(cat condition.txt); then
                            echo "[SKIPING] - Release Commit";
                            exit 0;
                          fi
                      - yarn install
            - step:
                  name: Compiling and Building the application
                  script:
                      - |
                          if $(cat condition.txt); then
                            echo "[SKIPING] - Release Commit";
                            exit 0;
                          fi
                      - echo "Building the application scripts";
            - step:
                  name: Creating a release
                  caches:
                      - node
                  script:
                      - |
                          if $(cat condition.txt); then
                            echo "[SKIPING] - Release Commit";
                            exit 0;
                          fi
                      - rm -f condition.txt
                      - yarn release
